### ISSUE TITLE
Error with 0.8.1 version

### ISSUE THREAD

**Issue by CZechBoY** [phpstan/playground#2]
Hi,
switch to version 0.8.1 give me this error:
```
Fatal error: Uncaught OutOfBoundsException: Required package "phpstan/phpstan" is not installed: cannot detect its version in <PHPStan>/vendor/ocramius/package-versions/src/PackageVersions/FallbackVersions.php:32
Stack trace:
#0 <PHPStan>/vendor/ocramius/package-versions/src/PackageVersions/Versions.php(27): PackageVersions\FallbackVersions::getVersion('phpstan/phpstan')
#1 <PHPStan>/vendor/jean85/pretty-package-versions/src/PrettyVersions.php(13): PackageVersions\Versions::getVersion('phpstan/phpstan')
#2 <PHPStan>/bin/phpstan(25): Jean85\PrettyVersions::getVersion('phpstan/phpstan')
#3 {main}
  thrown in <PHPStan>/vendor/ocramius/package-versions/src/PackageVersions/FallbackVersions.php on line 32
```

**Comment by ondrejmirtes** [comment]
Should be solved once phpstan.org notices 0.8.2.
